version: "3"

services:
  infra:
    build:
      context: ./infra
      # AWS CLIv2: https://docs.aws.amazon.com/ja_jp/cli/latest/userguide/getting-started-install.html
      # Terrafrom: https://developer.hashicorp.com/terraform/downloads
      # args:
        - AWS_CLI_URL=${AWS_CLI_URL:-https://awscli.amazonaws.com/awscli-exe-linux-aarch64.zip}
        - TERRAFORM_URL=${TERRAFORM_URL:-https://releases.hashicorp.com/terraform/1.3.6/terraform_1.3.6_linux_arm64.zip}
    image: venus_infra
    volumes:
      - ./infra:/infra
      - ~/.aws:/root/.aws:ro
    environment:
      - AWS_PROFILE=venus_terraform
  db:
    image: mysql:8.0
    platform: linux/amd64
    volumes:
      - db-data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
  backend:
    build: ./backend
    image: venus_backend
    ports:
      - 3000:3000
    volumes:
      - ./backend:/src
      - /src/tmp/pids
    environment:
      - DATABASE_URL=mysql2://root:root@db/venus
    depends_on:
      - db
    command: sh -c "rm -f tmp/pids/server.pid && bin/rails s -b 0.0.0.0 -p 3000"

volumes:
  db-data:
    driver: local
