name: Build docker image with layer cache
description: |
  Build docker image with layer cache
  See: https://github.com/docker/build-push-action
inputs:
  cache-key:
    description: Key for docker layer cache
    required: true
  context:
    description: Inputs for docker/build-push-action
    required: true
  tags:
    description: Inputs for docker/build-push-action
    required: true
  load:
    description: Inputs for docker/build-push-action
    required: true
  push:
    description: Inputs for docker/build-push-action
    required: true
  build-args:
    description: Inputs for docker/build-push-action
    required: false
    default: ""
runs:
  using: "composite"
  steps:
    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v2
    - name: Restore docker layer cache
      uses: actions/cache@v3
      with:
        path: /tmp/${{ inputs.cache-key }}/.buildx-cache
        key: ${{ inputs.cache-key }}-${{ github.ref }}-${{ github.sha }}
        restore-keys: |
          ${{ inputs.cache-key }}-${{ github.ref }}
          ${{ inputs.cache-key }}-refs/heads/main
    - name: Build image
      uses: docker/build-push-action@v3
      with:
        push: ${{ inputs.push }}
        builder: ${{ steps.buildx.outputs.name }}
        tags: ${{ inputs.tags }}
        load: ${{ inputs.load }}
        context: ${{ inputs.context }}
        build-args: ${{ inputs.args }}
        cache-from: type=local,src=/tmp/${{ inputs.cache-key }}/.buildx-cache
        cache-to: type=local,dest=/tmp/${{ inputs.cache-key }}/.buildx-cache-new
    # https://github.com/docker/build-push-action/issues/252
    # https://github.com/moby/buildkit/issues/1896
    - name: Move cache
      run: |
        rm -rf /tmp/${{ inputs.cache-key }}/.buildx-cache
        mv /tmp/${{ inputs.cache-key }}/.buildx-cache-new /tmp/${{ inputs.cache-key }}/.buildx-cache
