name: Build and push image
on:
  workflow_run:
    workflows: [Lint and test]
    types: [completed]
    branches: [main]
permissions:
  contents: read
env:
  AWS_REGION: ap-northeast-1
jobs:
  build-push-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: ${{ env.AWS_REGION }}
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/github-actions-role
      - uses: docker/login-action@v2
        with:
          registry: ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com
      - name: Build image
        uses: ./.github/actions/build-image
        with:
          cache-key: backend
          context: ./backend
          tags: ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/venus-backend:${{ github.sha }}
          load: false
          push: true
