name: Build and push image
on:
  workflow_run:
    workflows: [Lint and test]
    types: [completed]
    branches: [main]
permissions:
  contents: read
env:
  AWS_REGION: ap-northeast-1
  ECR_REPOSITORY_BACKEND: venus-backend
jobs:
  build-push-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}
      - uses: docker/login-action@v2
        with:
          registry: ${{ secrets.ECR_REGISTRY }}
      - name: Build image
        uses: ./.github/actions/build-image
        with:
          cache-key: backend
          context: ./backend
          tags: ${{ secrets.ECR_REGISTRY }}/${{ env.ECR_REPOSITORY_BACKEND }}:${{ github.sha }}
          load: false
          push: true
