name: Deploy sandbox to ECS
on:
  push:
    tags: ['sandbox**']
permissions:
  id-token: write
  contents: read
env:
  AWS_REGION: ap-northeast-1
jobs:
  deploy-backend-api:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Deploy backend
        uses: ./.github/actions/deploy
        with:
          app-name: venus
          app-env: sandbox
          image-uri: ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/venus-backend:${{ github.sha }}
          aws-account-id: ${{ secrets.AWS_ACCOUNT_ID }}
