name: Deploy sandbox to ECS
on:
  push:
    tags: ['sandbox**']
permissions:
  contents: read
jobs:
  deploy-backend-api:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Deploy backend
        uses: ./.github/actions/deploy
        with:
          app-name: venus
          app-env: sandbox
          image-uri: ${{ secrets.ECR_REGISTRY }}/venus-backend:${{ github.sha }}
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
