name: Deploy test to ECS
on: [push]
  # push:
  #   branches: [main]
  #   tags: [test**]
permissions:
  contents: read
env:
  APP_NAME: venus
  DEPROY_ENV: test
  AWS_REGION: ap-northeast-1
  ECR_REPOSITORY_BACKEND: venus-backend
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}
      - name: Build task definition
        run: |
          echo "TASK_DEFINITION_BACKEND_API<<EOF" >> $GITHUB_ENV
          echo $(infra/cmd/build_task_definition.sh \
                 backend_api
                 ${{ env.DEPROY_ENV }} \
                 ${{ env.APP_NAME }} \
                 ${{ secrets.ECR_REGISTRY }}/venus-backend:${{ github.sha }}) >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV
      - run: echo ${{ env.TASK_DEFINITION_BACKEND_API }}
