name: Deploy test to ECS
on:
  push:
    branches: ["main"]
    tags: ["test**"]
permissions:
  contents: read
env:
  APP_NAME: venus
  DEPROY_ENV: test
  AWS_REGION: ap-northeast-1
  ECR_REPOSITORY_BACKEND: venus-backend
jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      TASK_DEFINITION_BACKEND_API_PATH: infra/tmp/task_definition_backend_api.json
    steps:
      - uses: actions/checkout@v3
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}
      - name: Build task definition
        run: |
          infra/cmd/build_task_definition.sh \
            backend_api \
            ${{ secrets.ECR_REGISTRY }}/venus-backend:${{ github.sha }} \
            ${{ env.APP_NAME }} \
            ${{ env.DEPROY_ENV }} > ${{ env.TASK_DEFINITION_BACKEND_API_PATH }}
      - name: Deploy Amazon ECS task definition
        uses: aws-actions/amazon-ecs-deploy-task-definition@v1
        with:
          task-definition: ${{ env.TASK_DEFINITION_BACKEND_API_PATH }}
          cluster: ${{ env.APP_NAME }}-${{ env.DEPROY_ENV }}
          service: backend-api
          wait-for-service-stability: true
