name: Main
on: [push]
jobs:
  terraform-fmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: docker compose run --rm terraform ash -c "cd common && terraform fmt -diff=true -check=true"
      - run: docker compose run --rm terraform ash -c "cd staging && terraform fmt -diff=true -check=true"
  backend-lint-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build image
        run: docker compose build backend
      - name: Up container
        run: docker compose up db -d
      - run: sleep 3
      - name: Create db and load schema
        run: docker compose run --rm --no-deps backend bash -c "rails db:create db:schema:load RAILS_ENV=test"
      - name: Test
        run: docker compose run --rm --no-deps backend bash -c "rails test"
